# letsencrypt-staging-clusterissuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gateway
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: aim4highergg@gmail.com
    privateKeySecretRef:
      name: gateway-acme-account-key
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: envoy
            namespace: envoy-gateway