role: "Stateless-Aggregator"
replicas: 4
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1024Mi
service:
  ports:
    - name: vector
      protocol: TCP
      port: 8686
      targetPort: 8686
    - name: promtail
      protocol: TCP
      port: 9080
      targetPort: 9080
    - name: prometheus
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: loki
      protocol: TCP
      port: 3100
      targetPort: 3100
customConfig:
  api:
    enabled: true
    address: 127.0.0.1:8686
    playground: false
  sources:
    promtail-sources:
      type: http
      address: 0.0.0.0:9080
    prometheus-sources:
      type: prometheus_remote_write
      address: 0.0.0.0:9090
  transforms:
    promtail-transforms:
      type: remap
      inputs: [promtail-sources]
      source: |
        .timestamp = now()
  sinks:
    loki:
      type: loki
      inputs: [promtail-transforms]
      endpoint: http://monitoring-frontend-loki-write01-001.monitoring.svc.cluster.local:3100/loki/api/v1/push
      encoding:
        codec: json
      labels:
        job: promtail-via-vector
    victoria-logs-cluster:
      type: loki
      inputs: [promtail-transforms]
      endpoint: http://victoria-logs-cluster-vlinsert.monitoring.svc.cluster.local:9481/insert/loki/
      compression: gzip
      path: /api/v1/push?_msg_field=log&_time_field=timestamp&_stream_fields=namespace,container,pod
      labels:
        job: promtail-via-vector
      encoding:
        codec: json
    mimir:
      type: prometheus_remote_write
      inputs: [prometheus-sources]
      endpoint: http://monitoring-mimir-01-001.monitoring.svc.cluster.local:8080/api/v1/push
    victoria-metrics-cluster:
      type: prometheus_remote_write
      inputs: [prometheus-sources]
      endpoint: http://victoria-metrics-cluster-vminsert.monitoring.svc.cluster.local:8480/insert/0/prometheus/api/v1/write
      healthcheck:
        enabled: false