role: "Stateless-Aggregator"
replicas: 4
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1024Mi
service:
  ports:
    - name: vector
      protocol: TCP
      port: 8686
      targetPort: 8686
    - name: promtail
      protocol: TCP
      port: 9080
      targetPort: 9080
    - name: prometheus
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: loki
      protocol: TCP
      port: 3100
      targetPort: 3100

customConfig:
  api:
    enabled: true
    address: 127.0.0.1:8686
    playground: false

  sources:
    promtail-loki:
      type: http
      address: 0.0.0.0:9080

    promtail-victoria-logs:
      type: http
      address: 0.0.0.0:9081

    prometheus-mimir:
      type: prometheus_remote_write
      address: 0.0.0.0:9090

    prometheus-victoria-metrics:
      type: prometheus_remote_write
      address: 0.0.0.0:9091

  transforms:
    promtail-loki-transform:
      type: remap
      inputs: [promtail-loki]
      source: |
        .structured = parse_json!(.message)
        .timestamp = parse_timestamp!(.structured.values[0][0], "unix_ns")
        .log = .structured.values[0][1]
        .namespace = .structured.stream.namespace
        .pod = .structured.stream.pod_name
        .container = .structured.stream.container_name

    promtail-victoria-logs-transform:
      type: remap
      inputs: [promtail-victoria-logs]
      source: |
        .structured = parse_json!(.message)
        .timestamp = parse_timestamp!(.structured.values[0][0], "unix_ns")
        .log = .structured.values[0][1]
        .namespace = .structured.stream.namespace
        .pod = .structured.stream.pod_name
        .container = .structured.stream.container_name

    prometheus-mimir-transform:
      type: remap
      inputs: [prometheus-mimir]
      source: |
        .timestamp = now()

    prometheus-victoria-metrics-transform:
      type: remap
      inputs: [prometheus-victoria-metrics]
      source: |
        .timestamp = now()

  sinks:
    promtail-loki-sink:
      type: loki
      inputs: [promtail-loki-transform]
      endpoint: http://monitoring-frontend-loki-write01-001.monitoring.svc.cluster.local:3100
      path: /loki/api/v1/push
      compression: snappy
      encoding:
        codec: json
      labels:
        job: promtail-via-vector
      healthcheck:
        enabled: false

    promtail-victoria-logs-sink:
      type: loki
      inputs: [promtail-victoria-logs-transform]
      endpoint: http://victoria-logs-cluster-vlinsert.monitoring.svc.cluster.local:9481/insert/loki
      path: /api/v1/push?_msg_field=log&_time_field=timestamp&_stream_fields=namespace,container,pod
      compression: gzip
      encoding:
        codec: json
      labels:
        job: promtail-via-vector
      healthcheck:
        enabled: false

    prometheus-mimir-sink:
      type: prometheus_remote_write
      inputs: [prometheus-mimir-transform]
      endpoint: http://monitoring-mimir-01-001.monitoring.svc.cluster.local:8080/api/v1/push
      healthcheck:
        enabled: false

    prometheus-victoria-metrics-sink:
      type: prometheus_remote_write
      inputs: [prometheus-victoria-metrics-transform]
      endpoint: http://victoria-metrics-cluster-vminsert.monitoring.svc.cluster.local:8480/insert/0/prometheus/api/v1/write
      healthcheck:
        enabled: false
