---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: viteful-backend
  labels:
    app: viteful-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: viteful-backend
  template:
    metadata:
      labels:
        app: viteful-backend
    spec:
      imagePullSecrets:
        - name: registry
      containers:
        - name: backend
          image: <path:secret/data/viteful/registry#BACKEND_IMAGE>:0.1.0
          ports:
            - containerPort: 1323
          env:
            - name: DB_HOST
              value: viteful-db
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: viteful-db-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: viteful-db-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: viteful-db-secret
                  key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: viteful-backend
  labels:
    app: viteful-backend
spec:
  type: ClusterIP
  selector:
    app: viteful-backend
  ports:
    - name: http
      port: 1323
      targetPort: 1323
