controller:
  type: daemonset
  hostPID: true
  volumes:
    extra:
      - name: varlog
        hostPath:
          path: /var/log
      - name: journald
        hostPath:
          path: /run/log/journal
      - name: dockercontainers
        hostPath:
          path: /var/lib/docker/containers

  extraContainers: []
  initContainers: []

alloy:
  mounts:
    varlog: true
    dockercontainers: true
    extra:
      - name: journald
        mountPath: /run/log/journal
        readOnly: true

  securityContext:
    privileged: true
    runAsUser: 0

  configMap:
    create: true
    content: |
      logging {
        level = "info"
      }

      loki.source.files {
        include = ["/var/log/**/*.log"]
        labels = {
          job = "varlog"
        }
      }

      loki.source.journald {
        directory = "/run/log/journal"
        labels = {
          job = "journald"
        }
      }

      loki.source.kubernetes {
        cluster_name = "my-cluster"
      }

      loki.write {
        endpoint {
          url = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
        }
      }
