apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-gateway-proxy
  namespace: envoy-gateway 
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
        annotations:
          metallb.io/address-pool: envoy-gateway
          metallb.io/loadBalancerIPs: 192.168.1.104
