apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: prefixsuffix-transformer
suffix: -<path:secret/data/viteful/production/env#VITE_LOCATION_NAME_1>
fieldSpecs:
  - path: metadata/name
  - path: metadata/labels/app
  - path: spec/selector/matchLabels/app
  - path: spec/template/spec/containers/name
  - path: spec/template/spec/containers/env/valueFrom/secretKeyRef/name

