helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: "1.9.0"
    releaseName: longhorn
    namespace: longhorn-system
    valuesFile: ../values.yaml
    additionalValuesFiles:
      - additional-values.yaml
