helmCharts:
  - name: base
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.25.1
    releaseName: istio-base
    namespace: istio-system
    includeCRDs: true

  - name: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.25.1
    releaseName: istiod
    namespace: istio-system
    valuesFile: ../istiod-values.yaml

  - name: gateway
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.25.1
    releaseName: istio-ingress
    namespace: istio-system
    additionalValuesFiles:
      - additional-istio-ingress-values.yaml
    valuesFile: ../istio-ingress-values.yaml