# templates/virtualservice.yaml

{{- range $name, $svc := .Values.services }}
{{- if and $svc.enabled $svc.virtualService }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $name }}-virtualservice
  namespace: {{ $svc.gateway.namespace }}
spec:
  hosts:
    - {{ include "istio-gateway-aggregator.prefixedHost" (dict "Values" $.Values "hostname" $svc.hostname) }}
  gateways:
    - {{ $svc.gateway.name }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ $svc.virtualService.destinationHost }}
            port:
              number: {{ $svc.virtualService.destinationPort }}
---
{{- end }}
{{- end }}
