apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: <path:secret/data/viteful/production/namespace#NAMESPACE>
resources:
  - ../../base/frontend
  - avp-secret.yaml
transformers:
  - prefix-suffix-transformer.yaml
commonLabels:
  app: viteful-frontend-<path:secret/data/viteful/production/env#VITE_LOCATION_NAME_2>
patches:
  - target:
      version: v1
      group: apps
      kind: Service
      name: viteful-frontend
    patch: |-
      - op: replace
        path: /spec/selector/app
        value: viteful-frontend-<path:secret/data/viteful/production/env#VITE_LOCATION_NAME_2>
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: viteful-frontend
    patch: |-
      - op: replace
        path: /spec/selector/matchLabels/app
        value: viteful-frontend-<path:secret/data/viteful/production/env#VITE_LOCATION_NAME_2>
