helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: "1.7.2"
    releaseName: longhorn
    namespace: longhorn-system
    valuesFile: ../values.yaml
    additionalValuesFiles:
      - additional-values.yaml
    valuesMerge: override
    valuesInline:
      persistence:
        defaultFsType: ext4