apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: arc-runner-terraform-helm-argocd
  namespace: arc-runner
spec:
  replicas: 2
  template:
    spec:
      repository: AbeYuki/terraform-helm-argocd
