#kubectl label ns argocd trust-manager/bundle=enabled --overwrite
#kubectl label ns vault trust-manager/bundle=enabled --overwrite
#kubectl -n cert-manager get secret vault-root-ca-secret -o jsonpath='{.data.tls\.crt}' \
# | base64 -d \
# | kubectl -n cert-manager create configmap vault-ca-bundle --from-file=ca.pem=/dev/stdin
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: vault-trust-bundle
spec:
  sources:
    - configMap:
        name: vault-ca-bundle
        key: ca.pem
  target:
    configMap:
      key: ca.pem
    namespaceSelector:
      matchLabels:
        trust-manager/bundle: "enabled"