---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-aimhighergg-com
  namespace: monitoring
spec:
  parentRefs: # どの gateway 配下で有効にするかの紐づけ
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy
      namespace: envoy-gateway
  hostnames:
    - grafana.aimhighergg.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: monitoring-frontend-grafana-app01-001
          port: 80