# 認証局(CA)
## SelfSigned で Root CA をブートストラップ
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
## Root CA を自己署名で作成(ingress と同じ namespace にする必要あり)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-root-ca
  namespace: vault
spec:
  isCA: true
  commonName: vault-root-ca
  secretName: vault-root-ca-secret
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
## この CA で Vault サーバ・クライアント証明書を発行
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-ca-issuer
spec:
  ca:
    secretName: vault-root-ca-secret  # 上記の Root CA の Secret
---
# 自己署名証明書
## Vault サーバ証明書(共通証明書)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-server-cert
  namespace: vault
spec:
  secretName: vault-ha-tls
  issuerRef:
    name: vault-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: vault.vault.svc
  dnsNames:
    - vault
    - vault.vault
    - vault.vault.svc
    - vault.vault.svc.cluster.local
    - vault-0.vault-internal
    - vault-1.vault-internal
    - vault-2.vault-internal
    - vault.aimhighergg.com
    - staging.vault.aimhighergg.com
    - internal.aimhighergg.com
  ipAddresses:
    - 127.0.0.1
  usages:
    - digital signature
    - key encipherment
    - server auth
---
## argocd-repo-server 用の Vault クライアント証明書
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-client-cert
  namespace: argocd
spec:
  secretName: vault-client-tls
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: vault-ca-issuer
    kind: ClusterIssuer
  commonName: argocd-vault-plugin
  dnsNames:
    - argocd-repo-server.argocd.svc
  usages:
    - digital signature
    - key encipherment
    - client auth
---
## vault 用の クライアント証明書
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-client-tls
  namespace: vault 
spec:
  secretName: vault-client-tls
  duration: 2160h
  renewBefore: 360h 
  issuerRef:
    name: vault-ca-issuer
    kind: ClusterIssuer
  commonName: vault.vault.svc.cluster.local
  dnsNames:
    - vault.vault.svc.cluster.local
  usages:
    - digital signature
    - key encipherment
    - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-web-client-cert
  namespace: vault
spec:
  secretName: vault-web-client-tls
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: vault-ca-issuer
    kind: ClusterIssuer
  commonName: vault-web-client
  dnsNames:
    - internal.aimhighergg.com
  usages:
    - digital signature
    - key encipherment
    - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-internal-ingress-tls
  namespace: vault
spec:
  secretName: vault-internal-ingress-tls
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: vault-ca-issuer
    kind: ClusterIssuer
  commonName: internal.aimhighergg.com
  dnsNames:
    - internal.aimhighergg.com
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-ui
  namespace: vault
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/auth-tls-secret: "vault/vault-root-ca-secret"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    nginx.ingress.kubernetes.io/proxy-ssl-secret: "vault/vault-web-client-tls"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "on"
    nginx.ingress.kubernetes.io/proxy-ssl-name: "vault.vault.svc.cluster.local"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - internal.aimhighergg.com
    secretName: vault-internal-ingress-tls
  rules:
    - host: internal.aimhighergg.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault
                port:
                  number: 8200