apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-ca
  namespace: vault
spec:
  isCA: true
  commonName: vault-ca
  secretName: vault-ca
  duration: 87600h # 10 year
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-ca-issuer
  namespace: vault
spec:
  ca:
    secretName: vault-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-server
  namespace: vault
spec:
  secretName: vault-ha-tls
  duration: 8760h
  renewBefore: 360h
  subject:
    organizations:
      - HashiCorp
  commonName: vault.vault.svc
  dnsNames:
    - vault
    - vault.vault
    - vault.vault.svc
    - vault.vault.svc.cluster.local
    - "*.vault-internal"
    - "*.vault-internal.vault.svc.cluster.local"
  ipAddresses:
    - 127.0.0.1
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: vault-ca-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-client
  namespace: vault
spec:
  secretName: vault-client-tls
  duration: 8760h
  renewBefore: 360h
  subject:
    organizations:
      - VaultClient
  commonName: vault-client
  usages:
    - digital signature
    - key encipherment
    - client auth
  issuerRef:
    name: vault-ca-issuer
    kind: Issuer