global:
  tlsDisable: false
injector:
  enabled: true
  extraEnvironmentVars:
    VAULT_API_ADDR: "https://vault.vault.svc.cluster.local:8200"
    VAULT_ADDR: https://vault.vault.svc:8200
    VAULT_CACERT: /vault/userconfig/vault-ha-tls/ca.crt
    VAULT_CLIENT_CERT: /vault/userconfig/vault-client-tls/tls.crt
    VAULT_CLIENT_KEY: /vault/userconfig/vault-client-tls/tls.key
  volumes:
    - name: userconfig-vault-ha-tls
      secret:
        secretName: vault-ha-tls
    - name: vault-client-tls
      secret:
        secretName: vault-client-tls
  volumeMounts:
    - name: userconfig-vault-ha-tls
      mountPath: /vault/userconfig/vault-ha-tls
      readOnly: true
    - name: vault-client-tls
      mountPath: /vault/userconfig/vault-client-tls
      readOnly: true
  certs:
    tlsSecretName: vault-ha-tls
server:
  dataStorage:
    enabled: true
    size: 10Gi
    mountPath: "/vault/data"
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
    annotations: {}
    labels: {}
  extraEnvironmentVars:
    VAULT_CACERT: /vault/userconfig/vault-ha-tls/ca.crt
    VAULT_CLIENT_CERT: /vault/userconfig/vault-client-tls/tls.crt
    VAULT_CLIENT_KEY: /vault/userconfig/vault-client-tls/tls.key
    VAULT_TLS_REQUIRE_AND_VERIFY_CLIENT_CERT: "true"
  volumes:
    - name: userconfig-vault-ha-tls
      secret:
        secretName: vault-ha-tls
    - name: vault-client-tls
      secret:
        secretName: vault-client-tls
  volumeMounts:
    - name: userconfig-vault-ha-tls
      mountPath: /vault/userconfig/vault-ha-tls
      readOnly: true
    - name: vault-client-tls
      mountPath: /vault/userconfig/vault-client-tls
      readOnly: true
  ha:
    enabled: true
    replicas: 3
    apiAddr: https://vault.vault.svc.cluster.local:8200
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true
        api_addr = "https://vault.vault.svc.cluster.local:8200"
        listener "tcp" {
          tls_require_and_verify_client_cert = "true"
          tls_disable = 0
          tls_cert_file = "/vault/userconfig/vault-ha-tls/tls.crt"
          tls_key_file  = "/vault/userconfig/vault-ha-tls/tls.key"
          tls_client_ca_file = "/vault/userconfig/vault-ha-tls/ca.crt"
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          telemetry {
            unauthenticated_metrics_access = "true"
          }
        }
        storage "raft" {
          path = "/vault/data"
          tls_cert_file = "/vault/userconfig/vault-client-tls/tls.crt"
          tls_key_file  = "/vault/userconfig/vault-client-tls/tls.key"
          tls_client_ca_file = "/vault/userconfig/vault-ha-tls/ca.crt"
          retry_join {
            leader_api_addr = "https://vault-0.vault-internal:8200"
          }
          retry_join {
            leader_api_addr = "https://vault-1.vault-internal:8200"
          }
          retry_join {
            leader_api_addr = "https://vault-2.vault-internal:8200"
          }
        }
        service_registration "kubernetes" {}
ui:
  enabled: true
  serviceType: "ClusterIP"
  serviceNodePort: null
  externalPort: 8200
  targetPort: 8200
