apiVersion: v1
kind: ConfigMap
metadata:
  name: vmalert-rules
  namespace: monitoring
data:
  metrics-rules.yaml: |
    groups:
      - name: system
        rules:
        - alert: HighLoadAVG
          expr: "node_load15 > 10"
          labels:
            severity: critical
          annotations:
            summary: " {{ $labels.instance }} でロードアベレージが高騰"
            description: "topでプロセスのCPU使用率、ps -efで滞留プロセス、iostatでI/Oのボトルネック、vmstatでリソース状況確認"
      - name: server
        rules:
        - alert: PrometheusDown
          expr: "absent(count_over_time(prometheus_ready[15m]))"
          labels:
            severity: page
          annotations:
            summary: "Instance {{ $labels.instance }} down"
            description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
        - alert: LowRemoteStorageRate
          expr: rate(prometheus_remote_storage_samples_total[10m]) < 500
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Low remote storage rate detected"
            description: "The rate of prometheus_remote_storage_samples_total is below 500 (current value: {{ $value }})"
        - alert: NfsServerDown
          expr: namedprocess_namegroup_num_procs{groupname="rpc.idmapd"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "NFS Server process is DOWN"
            description: "rpc.idmapd プロセスが (current value: {{ $value }})"
      - name: kubernetes
        rules:
        - alert: scheduler_pending_pods
          expr: sum(scheduler_pending_pods) != 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Instance {{ $labels.instance }} scheduler pending pod"
            description: "POD is pending in {{ $labels.queue }} status for more than 5 minutes on {{ $labels.instance }}."
        - alert: longhor_backup_error
          expr: kube_custom_resouce_longhorn_backup_state_condition{state="Error"} == 1
          for: 0m
          labels:
            severity: alert
          annotations:
            summary: "Longhorn Backup PVC/{{$labels.backup_id}} Error"
            description: "PVC/{{$labels.backup_id}} が Longhorn Backup に失敗した"
        - alert: argocd_application_progressing
          expr: kube_custom_resouce_argocd_application_state{state="Progressing"} == 1
          for: 10m
          labels:
            severity: alert
          annotations:
            summary: "Argocd application {{$labels.app_name}} Progressing"
            description: "Argocd の application/{{$labels.app_name}} が Progressing 状態が継続している"
        - alert: argocd_application_degraded
          expr: kube_custom_resouce_argocd_application_state{state="Degraded"} == 1
          for: 5m
          labels:
            severity: alert
          annotations:
            summary: "Argocd application {{$labels.app_name}} Degraded"
            description: "Argocd の application/{{$labels.app_name}} が Degraded になった"
        - alert: pod_status_not_ready
          expr: kube_pod_status_ready{condition="false", pod!~"(production-backup|production-snapshot|production-trim).*"} == 1
          for: 5m
          labels:
            severity: alert
          annotations:
            summary: "NS/{{ $labels.namespace }} POD/{{ $labels.pod}} NotReady"
            description: "{{ $labels.namespace }}/{{ $labels.pod}} POD が Not Ready 状態が継続している"
        - alert: loki_ruler_cofig_reload_failed
          expr: 'irate(loki_ruler_sync_rules_total{reason="periodic"}[5m]) > 1'
          for: 0m
          labels:
            severity: alert
          annotations:
            summary: "Loki Ruler の config の reload に失敗"
            description: "Loki Ruler config のフォーマットに誤りがあるので修正してください"
      - name: service
        rules:
        - alert: ServiceDown
          expr: probe_http_status_code{instance="https://www.aimhighergg.com/", job="service"} != 200
          labels:
            severity: critical
          annotations:
            summary: "Service {{ $labels.instance }} down"
      - name: hardware
        rules:
          - alert: cpu_temperature_high
            expr: cpu_temperature > 90
            for: 0m
            labels:
              severity: critical
            annotations:
              summary: "{{ $labels.instance }} のCPU温度が {{ $value }} "
              description: "CPUクーラーの設定を調整してください"
      - name: pvc
        rules:
        - alert: HighPVCUsage
          expr: |
            100 * (
              sum by (namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes)
              /
              sum by (namespace, persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes)
            ) > 90
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "High PVC usage detected"
            description: "PVC {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} の使用率が90%超過"
      - name: server_resources
        rules:
        - alert: HighMemoryUsage
          expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 90
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "{{ $labels.instance }}でMemoryの使用率が90%超過"
            description: "Memmoryの使用率: (current value: {{ $value }}%)"
        - alert: HighCpuUsage
          expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "{{ $labels.instance }}でCPUの使用率が90%超過"
            description: "CPUの使用率: (current value: {{ $value }}%)"
      - name: kubernetes_resources
        rules:
        - alert: Utilization_of_allocated_CPU_resources
          expr: |
            (100 * (sum(rate(container_cpu_usage_seconds_total{container!="",container!="POD"}[5m])) by (namespace, pod)
                / sum(container_spec_cpu_quota{container!="",container!="POD"} / container_spec_cpu_period{container!="",container!="POD"}) by (namespace, pod))) > 90
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "{{ $labels.pod }} に割り当てられた CPU リソース上限に対する使用率が90%超過"
            description: "{{ $labels.pod }} に割り当てられた CPU リソース上限に対する使用率: (current value: {{ $value }}%)"
        - alert: Utilization_of_allocated_memory_resources
          expr: |
            (100 * (sum by (namespace, pod) (container_memory_usage_bytes{container!="",container!="POD"})
                / sum by (namespace, pod) (container_spec_memory_limit_bytes{container!="",container!="POD"} > 0))) > 90
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "{{ $labels.pod }} に割り当てられた memory リソース上限に対する使用率が90%超過"
            description: "{{ $labels.pod }} に割り当てられた memory リソース上限に対する使用率: (current value: {{ $value }}%)"
      - name: disk
        rules:
        - alert: node_disk_written_bytes_total
          expr: rate(node_disk_written_bytes_total{}[5m]) > 6000000
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "{{ $labels.instance }} の {{ $labels.device}} で書き込みレート超過"
            description: "{{ $labels.instance }} の {{ $labels.device}} でディスクに書き込まれたバイト数のレート（秒あたりのバイト数）: (current value: {{ $value }})"
        - alert: node_disk_io_time_seconds_total
          expr: rate(node_disk_io_time_seconds_total{}[5m]) > 1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "{{ $labels.instance }} の {{ $labels.device}} でディスクI/O操作に費やされた時間のレート超過"
            description: "{{ $labels.instance }} の {{ $labels.device}} でディスクI/O操作に費やされた時間のレート: (current value: {{ $value }})"
        - alert: node_disk_write_time_seconds_total
          expr: rate(node_disk_write_time_seconds_total{}[5m]) > 4
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "{{ $labels.instance }} の {{ $labels.device}} で書き込み操作に費やされた時間のレート超過"
            description: "{{ $labels.instance }} の {{ $labels.device}} で書き込み操作に費やされた時間のレート（秒あたりの時間）: (current value: {{ $value }})"
        
  logs-rules.yaml: |
    groups:
      - name: server
        interval: 1m
        rules:
        - alert: under_voltage_detected
          expr: 'count_over_time({job="journal"} |= "Undervoltage detected"[1m]) > 0'
          for: 0m
          labels:
            severity: warn
          annotations:
            summary: "Instance {{ $labels.node }} Under-voltage detected"
            description: "電圧不足のため電源交換を実施"
        - alert: system_err
          expr: 'count_over_time({job="journal",level="err"} | json [1m]) > 0'
          for: 0m
          labels:
            severity: error
          annotations:
            summary: "{{$labels.host}}の{{$labels.systemd_unit}}ユニットでエラー発生"
            description: "{{$labels.MESSAGE}}"
        - alert: system_crit
          expr: 'count_over_time({job="journal",level="crit"} | json [1m]) > 0'
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: "{{$labels.host}}の{{$labels.systemd_unit}}ユニットで致命的なエラー発生"
            description: "{{$labels.MESSAGE}}"
        - alert: journal_io_error
          expr: count_over_time({job="journal"} |= "log I/O erro"[1m]) > 1
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: "{{ $labels.host }} で I/O Error が発生"
            description: "ファイルシステムをアンマウントして修復してください。"
        - alert: journal_device_offline_error
          expr: 'count_over_time({job="journal"} |= "device offline error"[1m]) > 1'
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: "{{ $labels.host }} でデバイスのオフラインエラーが発生"
            description: "ディスクの損傷・接続不良などの問題の可能性がある。"
        - alert: journal_nfs_lost_lock
          expr: 'count_over_time({job="journal"} |~ "NFS: .+: lost .+ locks"[1m]) > 1'
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: "{{ $labels.host }} で NFS ファイルロックがロストした"
            description: "kubectl get all -A | grep <IP> で SERVICE/PVC を特定し PVC を再マウントする"
      - name: application
        interval: 1m
        rules:
        - alert: remote_storage_error
          expr: 'count_over_time({app_kubernetes_io_name="prometheus"}|detected_level="error" |="non-recoverable error"[5m]) > 0'
          for: 5m
          labels:
            severity: alert
          annotations:
            summary: "prometheus remote write error"
            description: "PrometheusのRemoteWrite周りを確認"
        - alert: oom_killer
          expr: 'count_over_time({job="journal"} |= "Memory cgroup out of memory"[1m]) > 0'
          for: 0m
          labels:
            severity: alert
            airflow_trigger: oom_killer
          annotations:
            summary: "Instance {{ $labels.node }} Memory cgroup out of memory"
            description: "アプリケーションがメモリ不足のためresourcesを調整する"
        - alert: unauthorized_access_detection
          expr: 'count_over_time({namespace="ingress-nginx"} |~ "HTTP/[1-2]\\.[0-2]\"\\s4[0-9]{2}\\s" |~ "/wp-login.php"[1m]) > 1'
          for: 0m
          labels:
            severity: alert
          annotations:
            summary: "wordpressのログインURLにアクセス試行"
            description: "アクセス内容を確認して必要であれば該当のIPをdenyに追加"
        - alert: vault_failed_to_heartbeat_to_peer
          expr: 'count_over_time({app_kubernetes_io_name="vault"}  |="storage.raft: failed to heartbeat to: peer"[1m]) > 0'
          for: 0m
          labels:
            severity: alert
          annotations:
            summary: "vault で raft peers のハートビート監視で失敗"
            description: "vault を確認して raft peers を構成してください"
        - alert: pod_input_output_error
          expr: 'count_over_time({pod_name=~".+"} | app_kubernetes_io_name != "loki" |= "input/output"[1m]) > 0'
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: "{{ $labels.pod_name }}でI/Oエラーが発生しました"
            description: "{{ $labels.pod_name }}のpodを再起動してください"
        - alert: minecraft_bedrock_server_user_connected
          expr: 'count_over_time({namespace="prod-minecraft"}|~ "Player connected"[10m]) > 0'
          for: 5m
          labels:
            severity: info
          annotations:
            summary: "Minecraft bedrock server user connected"
        - alert: longhorn_buckup_error
          expr: 'count_over_time({namespace="longhorn-system"} |= "cannot mount nfs"[1m]) > 0'
          for: 0m
          labels:
            severity: alert
          annotations:
            summary: "longhorn-system {{ $labels.node }} cannot mount nfs"
            description: "NFSサーバの状態確認を実施"
      - name: security
        interval: 1m
        rules:
        - alert: XMRigMiningAttempt
          expr: count_over_time({namespace="ingress-nginx",remote_addr!~"192\\.168\\..+"} |~ "mining"[1m]) > 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: "XMRig マイニングアクセスを検出"
        - alert: SQLInjectionAttempt
          expr: count_over_time({namespace="ingress-nginx",remote_addr!~"192\\.168\\..+"} |~ "UNION SELECT|DROP TABLE|OR 1=1|--|%27"[1m]) > 0
          for: 0m
          labels:
            severity: high
          annotations:
            summary: "SQLインジェクションの可能性あり"
        - alert: WordPressScan
          expr: count_over_time({namespace="ingress-nginx",remote_addr!~"192\\.168\\..+"} |~ "wp-login\\.php|xmlrpc\\.php|wp-admin"[1m]) > 0
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: "WordPress ターゲットのスキャン試行"
        - alert: Log4ShellAttempt
          expr: count_over_time({namespace="ingress-nginx",remote_addr!~"192\\.168\\..+"} |~ "\\$\\{jndi:[a-z]+://"[1m]) > 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: "Log4Shell 攻撃検出"
        - alert: PathTraversalAttempt
          expr: count_over_time({namespace="ingress-nginx",remote_addr!~"192\\.168\\..+"} |~ "\\.\\./|\\.\\.\\\\|%2e%2e%2f"[1m]) > 0
          for: 0m
          labels:
            severity: high
          annotations:
            summary: "パストラバーサル試行"
        - alert: SuspiciousUserAgent
          expr: count_over_time({namespace="ingress-nginx",remote_addr!~"192\\.168\\..+"} |~ "sqlmap|nikto|XMRig|curl"[1m]) > 0
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: "疑わしい User-Agent を検出"
        - alert: SshLoginFromOutsice
          expr: count_over_time({systemd_unit="ssh.service"} |="Accepted publickey" !="192.168"[1m]) > 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: "外部からSSHログイン"