apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: deny-filter
  namespace: www-aimhighergg-com
spec:
  directResponse:
    statusCode: 403
    contentType: text/plain
    body:
      type: Inline
      inline: "Forbidden"