controller:
  config:
  ingressClass: nginx
  ingressClassResource:
    name: "nginx"
  service:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: "192.168.1.100"
    externalTrafficPolicy: "Local"
    ipFamilyPolicy: SingleStack
    ipFamilies:
      - IPv4
    ports:
      http: 80
      https: 443
    targetPorts:
      http: http
      https: https
  kind: "Deployment"
  replicaCount: 2 
  dnsPolicy: "ClusterFirst"
  hostNetwork: false
  admissionWebhooks:
    enabled: true
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - ingress-nginx
        topologyKey: "kubernetes.io/hostname"