---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: monitoring
type: Opaque
stringData:
  .htpasswd: <path:secret/data/basic_auth#gateway>
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: argocd
type: Opaque
stringData:
  .htpasswd: <path:secret/data/basic_auth#gateway>
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: longhorn-system
type: Opaque
stringData:
  .htpasswd: <path:secret/data/basic_auth#gateway>
