mode: daemonset

image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.145.0"
  pullPolicy: IfNotPresent

presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: false
    storeCheckpoints: false

  kubernetesAttributes:
    enabled: true
    extractAllPodLabels: false
    extractAllPodAnnotations: false

# control plane の taint を許可
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

config:
  receivers:
    filelog:
      operators:
        - id: container-parser
          max_log_size: 102400
          type: container
        - id: try-json
          type: json_parser
          parse_from: body
          parse_to: attributes
          on_error: send
        - id: ensure-message
          type: add
          field: attributes.message
          value: EXPR(body)
          if: 'attributes.message == nil'
  exporters:
    # VictoriaLogs へ OTLP/HTTP Logs
    otlphttp/victorialogs:
      # VictoriaLogs が受ける Logs ingest endpoint  
      logs_endpoint: http://victoria-logs-cluster-vlinsert.monitoring.svc.cluster.local:9481/insert/opentelemetry/v1/logs
      #logs_endpoint: http://vector.monitoring.svc.cluster.local:4318/v1/logs
      # vmauth 経由の場合は Authorization やヘッダを付ける
      # headers:
      #   Authorization: "Bearer <token>"
  processors:
    # 低カーディナリティ：必要最低限の k8s メタデータだけを resource attribute として付与する場合
 #   k8sattributes:
 #     auth_type: serviceAccount
 #     extract:
 #       metadata:
 #         - k8s.namespace.name
 #         - k8s.pod.name
 #         - k8s.container.name
 #         - k8s.node.name
    # 高カーディナリティになりがちな属性を削る場合
    attributes/drop_high_card:
      actions:
        - key: request_id
          action: delete
        - key: trace_id
          action: delete
        - key: span_id
          action: delete
        - key: http.user_agent
          action: delete
        - key: client.address
          action: delete
        - key: url.full
          action: delete
  service:
    pipelines:
      logs:
        processors:
          - memory_limiter
          - k8sattributes
          - attributes/drop_high_card
          - batch
        exporters:
          - otlphttp/victorialogs
          - debug
