apiVersion: v1
kind: Secret
metadata:
  name: sakuracloud-dns-credentials
  namespace: cert-manager
stringData:
  accessToken: <path:secret/data/sakuracloud/credential#SAKURACLOUD_ACCESS_TOKEN>
  accessTokenSecret: <path:secret/data/sakuracloud/credential#SAKURACLOUD_ACCESS_TOKEN_SECRET>
