apiVersion: v1
kind: Secret
metadata:
  name: viteful-db-secret
type: Opaque
stringData:
  POSTGRES_USER: <path:secret/data/viteful/dev/db#POSTGRES_USER>
  POSTGRES_PASSWORD: <path:secret/data/viteful/dev/db#POSTGRES_PASSWORD>
  POSTGRES_DB: <path:secret/data/viteful/dev/db#POSTGRES_DB>
---
apiVersion: v1
kind: Secret
metadata:
  name: viteful-env-secret
type: Opaque
stringData:
  VITE_LOCATION_NAME: <path:secret/data/viteful/dev/env#VITE_LOCATION_NAME>
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  annotations:
    avp.kubernetes.io/path: "secret/data/container_registry"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: < dockerconfigjson | base64encode >
