apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
  AVP_AUTH_TYPE: "k8s"
  AVP_K8S_ROLE: "argocd"
  AVP_TYPE: "vault"
  VAULT_ADDR: "http://vault.vault.svc.cluster.local:8200"
  VAULT_SKIP_VERIFY: "true"
  VAULT_CACERT: "/etc/vault/ca/ca.pem"
  VAULT_CLIENT_CERT: "/etc/vault/tls/tls.crt"
  VAULT_CLIENT_KEY: "/etc/vault/tls/tls.key"