extraVolumes:
  - name: vault-ca
    secret:
      secretName: vault-root-ca

extraVolumeMounts:
  - name: vault-ca
    mountPath: /etc/ssl/certs/vault
    readOnly: true

extraEnv:
  - name: SSL_CERT_FILE
    value: /etc/ssl/certs/vault/ca.crt