volumes:
  - name: vault-root-ca
    secret:
      secretName: vault-root-ca
volumeMounts:
  - name: vault-root-ca
    mountPath: /etc/ssl/certs/vault-root-ca.crt
    subPath: ca.crt
    readOnly: true
extraEnv:
  - name: SSL_CERT_FILE
    value: /etc/ssl/certs/vault-root-ca.crt
