---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-trim
  namespace: longhorn-system
spec:
  cron: "30 0 * * *"
  task: "filesystem-trim"
  retain: 0
  concurrency: 1
  groups:
    - default