apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: production-snapshot
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 0 1 * * *
  groups:
  - production
  labels: {}
  name: production-snapshot
  parameters: {}
  retain: 7
  task: snapshot
