---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-snapshot
  namespace: longhorn-system
spec:
  cron: "0 */6 * * *"
  task: "snapshot"
  retain: 6
  concurrency: 1
  groups:
    - default