helmCharts:
- name: base
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.26.0
  releaseName: istio-base
  namespace: istio-system
  includeCRDs: true

- name: istiod
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.25.1
  releaseName: istiod
  namespace: istio-system
  valuesFile: ../values.yaml