controller:
  config:
    use-forwarded-headers: "true"
  kind: DaemonSet
  service:
    loadBalancerIP: "10.0.0.100"
  hostNetwork: true
  containerSecurityContext:
    capabilities:
      add:
        - NET_BIND_SERVICE