controller:
  hostNetwork: true
  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443
  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
  kind: "DaemonSet"
  service:
    externalTrafficPolicy: "Local"