controller:
  kind: Deployment
  service:
    enabled: true
    type: NodePort
    external:
      enabled: true
    enableHttp: true
    enableHttps: true
    ports:
      http: 80
      https: 443
    targetPorts:
      http: http
      https: https
    nodePorts:
      http: 30080
      https: 30443