helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: "4.11.3"
    releaseName: ingress-nginx
    namespace: ingress-nginx
    additionalValuesFiles:
      - additional-values.yaml
    valuesInline:
      controller:
        kind: "DaemonSet"
        dnsPolicy: "ClusterFirstWithHostNet"
        hostNetwork: true
        admissionWebhooks:
          enabled: true
        service:
          externalTrafficPolicy: "Local"