helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: "4.5.2"
    releaseName: ingress-nginx
    namespace: ingress-nginx
    valuesFile: ../values.yaml
    additionalValuesFiles:
      - additional-values.yaml
